[project]
name = "prompt"
version = "2.0.0"
description = "Craft your shell prompt in Rust"
homepage = "https://github.com/roguePanda/prompt"
repository = "https://github.com/roguePanda/prompt.git"
license = "Apache-2.0"
authors = ["Ben Navetta <ben.navetta@gmail.com>"]
edition = "2018"

[lib]
name = "prompt"

[[bin]]
name = "prompt_ben"

[dependencies]
git2 = "~0.8"
nix = "~0.12"